- become: true
  become_method: sudo
  connection: local
  hosts: localhost
  name: Set up local workstation for hpc
  roles:
    - role: base
      vars:
        elrepo: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
        yum_baseline_upgrade: true
        yum_kernel_upgrade: true
    - role: nvidia.nvidia_driver
      vars:
        nvidia_driver_skip_reboot: "yes"
    - role: google-chrome
    - role: geerlingguy.git
      vars:
        git_install_from_source: true
        git_install_from_source_force_update: true
        git_install_path: "/usr/local"
        git_version: "2.25.1"
    - role: ngetchell.vscode
      vars:
        vscode_extension:
          - aaron-bond.better-comments
          - eamodio.gitlens
          - esbenp.prettier-vscode
          - ms-python.python
          - ms-python.vscode-pylance
          - ms-vscode-remote.remote-ssh
          - ms-vscode-remote.remote-ssh-edit
          - yzhang.markdown-all-in-one
    - role: andrewrothstein.anaconda
      vars:
        anaconda_install_channels: "defaults conda-forge"
        anaconda_install_packages:
          - autoflake
          - autopep8
          - awscli
          - aws-sam-cli
          - black
          - glances
          - ipython
          - isort
          - jupyter
          - pylint
          - ranger-fm
          - yq
        anaconda_parent_dir: /opt
        ys_default: true
    - role: geerlingguy.nodejs
      vars:
        nodejs_npm_global_packages:
          - create-react-app
          - eslint
        nodejs_version: "14.x"
    - role: geerlingguy.docker
    - role: nvidia.nvidia_docker
    - role: geerlingguy.ntp
      vars:
        - ntp_area: hk
        - ntp_manage_config: true
        - ntp_servers:
            - "stdtime.gov.hk iburst"
            - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
        - ntp_timezone: Asia/Hong_Kong
    - role: geerlingguy.security
      vars:
        security_autoupdate_enabled: false
        security_fail2ban_enabled: false
        security_ssh_challenge_response_auth: "no"
        security_ssh_gss_api_authentication: "no"
        security_ssh_password_authentication: "yes"
        security_ssh_permit_empty_password: "no"
        security_ssh_permit_root_login: "no"
        security_ssh_restart_handler_state: restarted
        security_ssh_usedns: "no"
        security_ssh_x11_forwarding: "yes"
    - role: intel-psxe
      vars:
        install_psxe: true
        install_runtime: false
        psxe_activation_config: ACTIVATION_SERIAL_NUMBER=
        psxe_activation_type: serial_number
        psxe_download_url: https://registrationcenter-download.intel.com/akdlm/irc_nas/tec/17113/parallel_studio_xe_2020_update4_cluster_edition.tgz
        psxe_temp_root: /tmp
  tasks:
    - name: misc packages
      yum:
        name:
          - curl
          - nano
          - vim
          - wget
        state: latest
