# Jetpack: https://developer.nvidia.com/embedded/jetpack
- become: true
  become_method: sudo
  hosts: all
  name: Set up jetson nano for inference
  roles:
    - role: geerlingguy.nodejs
      vars:
        nodejs_version: "14.x"
    - role: geerlingguy.ntp
      vars:
        - ntp_area: hk
        - ntp_manage_config: true
        - ntp_servers:
            - "stdtime.gov.hk iburst"
            - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
        - ntp_timezone: Asia/Hong_Kong
    - role: geerlingguy.security
      vars:
        security_autoupdate_enabled: false
        security_fail2ban_enabled: false
        security_ssh_challenge_response_auth: "no"
        security_ssh_gss_api_authentication: "no"
        security_ssh_password_authentication: "yes"
        security_ssh_permit_empty_password: "no"
        security_ssh_permit_root_login: "no"
        security_ssh_restart_handler_state: restarted
        security_ssh_usedns: "no"
        security_ssh_x11_forwarding: "yes"
    - role: jetson_nano.python
    - role: jetson_nano.opencv
    - role: jetson_nano.pytorch
    - role: jetson_nano.tensorflow
  tasks:
    - name: Misc packages
      apt:
        name:
          - curl
          - nano
          - vim
          - wget
        update_cache: yes
