- src: andrewrothstein.anaconda
- src: geerlingguy.docker
- src: geerlingguy.git
- src: geerlingguy.nodejs
- src: geerlingguy.ntp
- src: geerlingguy.security
- name: ngetchell.vscode
  src: https://github.com/ngetchell/vscode
  version: master
- src: nvidia.nvidia_docker
- src: nvidia.nvidia_driver
