- src: andrewrothstein.anaconda
- src: geerlingguy.docker
- src: geerlingguy.nodejs
- src: geerlingguy.ntp
- src: geerlingguy.security
- src: https://github.com/ngetchell/vscode
  version: master
  name: ngetchell.vscode
- src: nvidia.nvidia_docker
