---
- name: Set up local workstation
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  roles:
    - role: nvidia.nvidia_driver
      vars:
        nvidia_driver_skip_reboot: "yes"
    - role: geerlingguy.docker
    - role: nvidia.nvidia_docker
