---
- name: Set up local workstation
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  roles:
    - role: base
      vars:
        elrepo: https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    - role: geerlingguy.docker
    - role: nvidia.nvidia_docker
    - role: andrewrothstein.anaconda
      vars:
        anaconda_install_channels: "defaults conda-forge"
        anaconda_install_packages:
          - autopep8
          - awscli
          - aws-sam-cli
          - black
          - ffmpeg
          - glances
          - gstreamer
          - gst-plugins-base
          - gst-plugins-good
          - ipython
          - jupyter
          - luigi
          - matplotlib
          - numpy
          - pandas
          - pylint
          - ranger-fm
          - yq
          - scipy
        ys_default: true
        anaconda_parent_dir: /opt
    - role: geerlingguy.nodejs
      vars:
        nodejs_version: "12.x"
        nodejs_npm_global_packages:
          - create-react-app
          - eslint
          - firebase-tools
          - gatsby-cli
          - serve
    - role: ngetchell.vscode
      vars:
        vscode_extension:
          - aaron-bond.better-comments
          - eamodio.gitlens
          - esbenp.prettier-vscode
          - graphql.vscode-graphql
          - ms-vscode-remote.remote-ssh
          - ms-vscode-remote.remote-ssh-edit
          - ms-python.python
    - role: geerlingguy.ntp
      vars:
        - ntp_area: hk
        - ntp_manage_config: true
        - ntp_servers:
            - "stdtime.gov.hk iburst"
            - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
        - ntp_timezone: Asia/Hong_Kong
    - role: geerlingguy.security
      vars:
        security_autoupdate_enabled: false
        security_fail2ban_enabled: false
        security_ssh_challenge_response_auth: "no"
        security_ssh_gss_api_authentication: "no"
        security_ssh_password_authentication: "yes"
        security_ssh_permit_empty_password: "no"
        security_ssh_permit_root_login: "no"
        security_ssh_restart_handler_state: restarted
        security_ssh_usedns: "no"
        security_ssh_x11_forwarding: "yes"
        security_sudoers_passwordless:
          - kftse
    - role: intel-psxe
      vars:
        install_runtime: false
        install_psxe: true
        psxe_download_url: https://registrationcenter-download.intel.com/akdlm/irc_nas/tec/17113/parallel_studio_xe_2020_update4_cluster_edition.tgz
        psxe_temp_root: /tmp
        # exist_lic, license_server, license_file, serial_number
        psxe_activation_type: serial_number
        # ACTIVATION_LICENSE_FILE=filepat, lspat
        # ACTIVATION_SERIAL_NUMBER=snpat
        psxe_activation_config: ACTIVATION_SERIAL_NUMBER=
    - role: google-chrome
  tasks:
  - name: misc packages
    yum:
      name:
        - GraphicsMagick
        - htop
        - snapd
        - sox
        - tmux
      state: latest