---
- name: Set up local workstation
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  roles:
    - role: base
      vars:
        yum_baseline_upgrade: true
        yum_kernel_upgrade: true
    - role: nvidia-cuda
    - role: intel-psxe
      vars:
        - install_runtime: false
        - install_psxe: true
        - psxe_activation_type: serial_number
        - psxe_activation_config: ACTIVATION_SERIAL_NUMBER=
    - role: andrewrothstein.anaconda
      vars:
        anaconda_install_channels: "defaults conda-forge"
        anaconda_install_packages:
          - ipython
          - jupyter
          - matplotlib
          - numpy
          - pandas
          - pylint
          - scipy
        ys_default: true
        anaconda_parent_dir: /opt
    - role: geerlingguy.nodejs
      vars:
        nodejs_version: "12.x"
        nodejs_npm_global_packages:
          - "@aws-amplify/cli"
          - firebase-tools
          - gatsby-cli
          - create-react-app
          - serve
    - role: geerlingguy.git
      vars:
        git_install_from_source: true
        git_install_from_source_force_update: true
        git_install_path: "/usr/local"
        git_version: "2.25.1"
    - role: ngetchell.vscode
      vars:
        vscode_extension:
          - aaron-bond.better-comments
          - eamodio.gitlens
          - esbenp.prettier-vscode
          - ms-vscode-remote.remote-ssh
          - ms-vscode-remote.remote-ssh-edit
    - role: geerlingguy.ntp
      vars:
        - ntp_area: hk
        - ntp_manage_config: true
        - ntp_servers:
            - "stdtime.gov.hk iburst"
            - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
            - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
        - ntp_timezone: Asia/Hong_Kong
    - role: geerlingguy.security
      vars:
        security_autoupdate_enabled: false
        security_fail2ban_enabled: true
        security_ssh_challenge_response_auth: "no"
        security_ssh_gss_api_authentication: "no"
        security_ssh_password_authentication: "yes"
        security_ssh_permit_empty_password: "no"
        security_ssh_permit_root_login: "no"
        security_ssh_restart_handler_state: restarted
        security_ssh_usedns: "no"
        security_ssh_x11_forwarding: "yes"
        security_sudoers_passwordless:
          - kftse
    - misc
