- local_action: stat path=/opt/intel
  register: psxe_install_path
- import_tasks: runtime.yml
  name: install intel psxe runtime
  when: install_runtime and not psxe_install_path.stat.exists
- import_tasks: psxe.yml
  name: install intel psxe
  when: install_psxe and not psxe_install_path.stat.exists
