- lineinfile:
    backrefs: true
    line: "SELINUX=disabled"
    path: /etc/selinux/config
    regexp: '^\s*SELINUX\s*=.*$'
    state: present
  name: Persistently Disabling SELinux
  when: ansible_facts['selinux']['status'] != "disabled"
- name: Upgrading Kernel
  when: yum_kernel_upgrade == true
  yum:
    name: "kernel*"
    state: latest
    update_cache: true
- name: Upgrading All Packages, Excluding Kernel
  when: yum_baseline_upgrade == true
  yum:
    exclude: kernel*
    name: "*"
    state: latest
    update_cache: true
- name: Installing ELRepo GPG Key
  rpm_key:
    fingerprint: 96C0 104F 6315 4731 1E0B B1AE 309B C305 BAAD AE52
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
- name: Installing ELRepo
  yum:
    name: "{{ elrepo }}"
- name: Installing CentOS SCL
  yum:
    name: centos-release-scl
