- name: install nvidia-detect
  yum:
    name: nvidia-detect
    update_cache: true

- name: run nvidia-detect
  command: 
    cmd: nvidia-detect
  register: nvidia_modules
  failed_when: nvidia_modules.rc == 0 or nvidia_modules.rc >= 6
  changed_when: false

- name: install nvidia driver
  yum:
    name: "{{ nvidia_modules.stdout_lines }}"
