- name: install nvidia-detect
  yum:
    name: nvidia-detect
    update_cache: true

- name: run nvidia-detect
  command: 
    cmd: nvidia-detect
  register: nvidia_modules
  failed_when: nvidia_modules.rc == 0 or nvidia_modules.rc >= 6
  changed_when: false

- name: install nvidia driver
  yum:
    name: "{{ nvidia_modules.stdout_lines }}"

- name: install cuda repos
  shell: 
    cmd: "yum-config-manager --add-repo {{ cuda_repo }}"
    creates: /etc/yum.repos.d/cuda-rhel7.repo

- name: install cuda
  yum:
    name: "cuda-{{cuda_version}}"
    update_cache: true

- name: create user for nvidia-persistenced
  user:
    comment: "User for nvidia-persistenced daemon"
    create_home: false
    local: true
    name: "{{ nvidia_persistenced_user }}"
    state: present
    system: true

- name: write persistenced service file
  template:
    src: nvidia-persistenced.service.j2
    dest: /etc/systemd/system/nvidia-persistenced.service
    owner: root
    group: root
    mode: 0644

- name: make sure nvidia-persistenced is running
  systemd:
    enabled: true
    name: nvidia-persistenced
    state: started

- name: enable nvprof for user
  template:
    src: nvprof.cfg.j2
    dest: /etc/modprobe.d/nvprof.conf
    owner: root
    group: root
    mode: 0644